# Generated by Django 5.1.1 on 2024-09-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenCharter',
            fields=[
                ('eval_id', models.AutoField(primary_key=True, serialize=False)),
                ('eval_citizenttype', models.CharField(default='1', max_length=50)),
                ('eval_date', models.CharField(default='', max_length=50)),
                ('eval_sex', models.CharField(default='0', max_length=1)),
                ('eval_age', models.IntegerField()),
                ('eval_region', models.CharField(default='', max_length=30)),
                ('eval_service', models.CharField(default='', max_length=30)),
                ('eval_cc1', models.IntegerField(default=0)),
                ('eval_cc2', models.IntegerField(default=0)),
                ('eval_cc3', models.IntegerField(default=0)),
                ('eval_sqd0', models.IntegerField(default=0)),
                ('eval_sqd1', models.IntegerField(default=0)),
                ('eval_sqd2', models.IntegerField(default=0)),
                ('eval_sqd3', models.IntegerField(default=0)),
                ('eval_sqd4', models.IntegerField(default=0)),
                ('eval_sqd5', models.IntegerField(default=0)),
                ('eval_sqd6', models.IntegerField(default=0)),
                ('eval_sqd7', models.IntegerField(default=0)),
                ('eval_sqd8', models.IntegerField(default=0)),
                ('eval_suggestion', models.CharField(default='', max_length=250)),
                ('eval_email', models.CharField(default='', max_length=30)),
                ('eval_name', models.CharField(default='', max_length=30)),
                ('eval_other', models.CharField(default='', max_length=100)),
                ('office_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tblcitizen',
            },
        ),
        migrations.CreateModel(
            name='TableOffice',
            fields=[
                ('office_id', models.AutoField(primary_key=True, serialize=False)),
                ('office_code', models.CharField(default='0', max_length=20)),
                ('office_desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbloffice',
            },
        ),
        migrations.CreateModel(
            name='TableProcess',
            fields=[
                ('process_id', models.AutoField(primary_key=True, serialize=False)),
                ('office_id', models.IntegerField(default=0)),
                ('process_desc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tblprocess',
            },
        ),
    ]
