# Generated by Django 4.2.16 on 2024-09-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0004_citizencharter_eval_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizencharter',
            name='office_id',
            field=models.IntegerField(default=0),
        ),
    ]
