# Generated by Django 4.2.14 on 2024-08-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0019_evaluations_delete_evaluation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evaluations',
            table='tblcsqm',
        ),
    ]
