# Generated by Django 4.2.14 on 2024-08-01 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0020_alter_evaluations_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evaluations',
            new_name='CitizenCharter',
        ),
        migrations.AlterModelTable(
            name='citizencharter',
            table='tblcitizen',
        ),
    ]
