# Generated by Django 4.2.14 on 2024-08-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0021_rename_evaluations_citizencharter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CitizenCharter',
        ),
    ]
